### PR TITLE
Week 5 (booking APIs / RWD Booking page)、Week 6 ( Tappay connection / Thank You page)

### PR DESCRIPTION
**Pull request by vivian-wj-lin**
玟均請求view, test links are as below:

http://35.79.12.159:3000/
http://35.79.12.159:3000/attraction/2
http://35.79.12.159:3000/booking

Thank a million!

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We should redirect user to homepage if they visit booking page without signing in.
2. Your layout exceeds screen width in middle size of devices.
3. Other layout details in booking page shown below:
35 79 12 159_3000_booking

**Comment by vivian-wj-lin** [comment]
1./2./3.    fixed. 
4.    week 6  contents added.

Thank a million for reviewing!

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. Don't show prime in alert dialog.
2. We have to delete booking data after successful ordering.

**Comment by vivian-wj-lin** [comment]
1. fixed. Prime is no longer showing up in alert dialog. 
2. fixed. Cart contents would be deleted after orders have been established.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
