### PR TITLE
week 2 ( RWD home page,  attractions loading, keyword search,  keyword auto-fill )

### PR DESCRIPTION
**Pull request by vivian-wj-lin**
玟均請求review，謝謝老師!
測試網址: 
http://35.79.12.159:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
A lot of layout issues: width, height, alignment, padding, margin, there should be no scroll bar for content inside.
未命名-2

**Review by cwpeng — CHANGES_REQUESTED** [review]
1. We should put category name into keyword input if we click one of them.
2. Layout issues in middle size devices, ex. iPad. Try set background size to cover in your hero image and do any necessary changes.

**Comment by vivian-wj-lin** [comment]
1. it has been fixed after I killed previous nohup process. 
2. adjustments has been made. 

Finger crossed for the review. Thanks a million!!

**Review by cwpeng — APPROVED** [review]
OK. Done. Keep Going.

**Pull request merged**
